apiVersion: 1

datasources:
  - name: Healthcare Claims Postgres
    uid: healthcare_claims_postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: claims_user
    secureJsonData:
      password: claims_password
    jsonData:
      database: claims_warehouse
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false